<a href="https://colab.research.google.com/github/tillurakesh3/Rakesh_INFO5731_Fall2024/blob/main/In_Class_Exercise_Combined_ipynb_(1)_(1)_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In-Class Exercise: Sentiment Analysis + Text Classification + Prompt Engineering

**Course:** NLP / Text Mining  
**Total Points:** 30  
**Suggested Time:** about 45 minutes total  
**Dataset:** `sentiment_classification_combined_data.csv`

**Instructions**
- Complete all questions in this notebook.
- Run all cells before submission.
- Keep your answers clear and organized.
- For the prompt engineering part, you do **not** need an API key.

## Part A — Sentiment Analysis with VADER (10 points)
In this part, use **VADER** to compute sentiment scores for the text data.

In [1]:
# Upload the dataset file from your computer (Google Colab)
from google.colab import files

uploaded = files.upload()
filename = next(iter(uploaded))
print("Uploaded file name:", filename)

Saving sentiment_classification_combined_data.csv to sentiment_classification_combined_data (1).csv
Uploaded file name: sentiment_classification_combined_data (1).csv

### Q1. Load and inspect the dataset (2 points)
Show:
1. the first 5 rows  
2. the shape of the dataset  
3. the column names

In [4]:
# Read the uploaded CSV file
# Q1. Load and inspect the dataset
import pandas as pd

# Load the dataset using the filename from the upload cell
df = pd.read_csv(filename)

# 1. Show the first 5 rows
print("First 5 rows:")
display(df.head())

# 2. Show the shape of the dataset
print("\nShape of the dataset:")
print(df.shape)

# 3. Show the column names
print("\nColumn names:")
print(df.columns.tolist())

First 5 rows:

                                                Text TrueLabel  Score
0  I loved this healthcare AI workshop. The examp...  positive      5
1  This lecture was okay, but some parts were con...   neutral      3
2  The notebook was easy to follow and very pract...  positive      5
3  I did not like the explanation of the model re...  negative      1
4  The activity was interesting and helped me und...  positive      4

Shape of the dataset:
(24, 3)

Column names:
['Text', 'TrueLabel', 'Score']

### Q2. Apply VADER to compute sentiment scores (3 points)
- Import VADER
- Download the lexicon if needed
- Create a new column called `compound`
- Show the first 5 rows of `Text` and `compound`

In [6]:
# Q2. Apply VADER to compute sentiment scores

# 1. Create a function or use a lambda to get the compound score
df['compound'] = df['Text'].apply(lambda x: sia.polarity_scores(x)['compound'])

# 2. Show the first 5 rows of 'Text' and 'compound'
display(df[['Text', 'compound']].head())

                                                Text  compound
0  I loved this healthcare AI workshop. The examp...    0.8555
1  This lecture was okay, but some parts were con...   -0.2263
2  The notebook was easy to follow and very pract...    0.4404
3  I did not like the explanation of the model re...   -0.2755
4  The activity was interesting and helped me und...    0.4019

In [ ]:
# Write your answer here

### Q3. Create a sentiment label from the compound score (3 points)
Create a new column called `PredictedSentiment` using this rule:
- `compound >= 0.05` → `positive`
- `compound <= -0.05` → `negative`
- otherwise → `neutral`

Then show the first 10 rows of `Text`, `compound`, and `PredictedSentiment`.

In [7]:
# Write your answer here
# Q3. Create a sentiment label from the compound score

# 1. Define the rule for labeling
def get_sentiment_label(score):
    if score >= 0.05:
        return 'positive'
    elif score <= -0.05:
        return 'negative'
    else:
        return 'neutral'

# 2. Create the PredictedSentiment column
df['PredictedSentiment'] = df['compound'].apply(get_sentiment_label)

# 3. Show the first 10 rows of Text, compound, and PredictedSentiment
display(df[['Text', 'compound', 'PredictedSentiment']].head(10))

,Text,compound,PredictedSentiment
0,I loved this healthcare AI workshop. The examp...,0.8555,positive
1,"This lecture was okay, but some parts were con...",-0.2263,negative
2,The notebook was easy to follow and very pract...,0.4404,positive
3,I did not like the explanation of the model re...,-0.2755,negative
4,The activity was interesting and helped me und...,0.4019,positive
5,The class was too fast and I could not follow ...,0.0000,neutral
6,"The topic is important, but the instructions w...",0.1027,positive
7,I really enjoyed the examples and the live cod...,0.5563,positive
8,The dataset was messy and the task felt frustr...,-0.6597,negative
9,The exercise was manageable and useful for pra...,0.4404,positive

### Q4. Compare review score and sentiment (2 points)
Group by `Score` and compute the **average compound score** for each score value.

In [8]:
# Write your answer here
# Q4. Compare review score and sentiment
# Group by Score and compute the average compound score for each score value

avg_sentiment_by_score = df.groupby('Score')['compound'].mean()

# Display the result
print("Average compound score by review score:")
print(avg_sentiment_by_score)

Average compound score by review score:
Score
1   -0.507033
2   -0.296125
3   -0.150783
4    0.478340
5    0.621167
Name: compound, dtype: float64

## Part B — Prompt Engineering (10 points)
This part is based on the **Prompt Engineering** notebook. You do **not** need an API key. Focus on writing better prompts using the concepts of **instruction, context, output format, zero-shot, few-shot, and chain-of-thought**.

In [ ]:
# Sample texts for the prompt engineering questions
sample_reviews = [
    "The product arrived late and the quality was poor.",
    "Amazing battery life and elegant design.",
    "It is fine for daily use, nothing special."
]
for i, text in enumerate(sample_reviews, start=1):
    print(f"{i}. {text}")

### Q1. Zero-shot classification prompt (3 points)
Write a **zero-shot prompt** that asks an AI model to classify each review as **positive, negative, or neutral**.

Your prompt should include:
- a clear instruction
- the three labels
- a request for a clean output format

Store your prompt in a Python variable called `zero_shot_prompt`, then print it.

In [9]:
# Write your answer here
# Q1. Zero-shot classification prompt

# Define the zero-shot prompt with clear instructions and labels
zero_shot_prompt = """
Instruction: Classify the sentiment of the following product reviews as either 'positive', 'negative', or 'neutral'.
Output format: Provide only the label for each review.

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.
"""

# Print the prompt
print(zero_shot_prompt)

Instruction: Classify the sentiment of the following product reviews as either 'positive', 'negative', or 'neutral'.
Output format: Provide only the label for each review.

Reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q2. Few-shot prompt improvement (3 points)
Now improve the previous prompt by adding **two examples**.

Requirements:
- Store it in a variable called `few_shot_prompt`
- Include 2 input-output examples
- Ask the model to classify the 3 sample reviews after the examples

In [10]:
# Write your answer here
# Q2. Few-shot prompt improvement

# Define the few-shot prompt with 2 examples and the 3 sample reviews
few_shot_prompt = """
Instruction: Classify the sentiment of product reviews as 'positive', 'negative', or 'neutral'.
Output format: Provide only the label for each review.

Example 1:
Review: "The delivery was fast and the item works perfectly!"
Label: positive

Example 2:
Review: "I'm disappointed; it broke after just two days."
Label: negative

Now classify the following reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.
"""

# Print the prompt
print(few_shot_prompt)

Instruction: Classify the sentiment of product reviews as 'positive', 'negative', or 'neutral'.
Output format: Provide only the label for each review.

Example 1:
Review: "The delivery was fast and the item works perfectly!"
Label: positive

Example 2:
Review: "I'm disappointed; it broke after just two days."
Label: negative

Now classify the following reviews:
1. The product arrived late and the quality was poor.
2. Amazing battery life and elegant design.
3. It is fine for daily use, nothing special.

### Q3. Prompt comparison and refinement (4 points)
Create a short table or DataFrame with **three columns**:
- `PromptType`
- `MainFeature`
- `WhyUseful`

Include these three prompt types:
1. Zero-shot
2. Few-shot
3. Chain-of-thought

Then, in **2–3 sentences**, explain which one you would choose for a more difficult text analysis task and why.

In [11]:
# Write your answer here
# Q3. Prompt comparison and refinement

# 1. Create the comparison DataFrame
data = {
    'PromptType': ['Zero-shot', 'Few-shot', 'Chain-of-thought'],
    'MainFeature': [
        'Direct instruction without examples',
        'Instruction with a few input-output examples',
        'Asking the model to "think step-by-step"'
    ],
    'WhyUseful': [
        'Quickest to write; tests model’s baseline knowledge',
        'Improves formatting and accuracy by showing patterns',
        'Breaks down complex logic; great for reasoning tasks'
    ]
}

df_comparison = pd.DataFrame(data)
display(df_comparison)

# 2. Short explanation
print("\nExplanation:")
print("For a more difficult text analysis task, I would choose Chain-of-thought prompting.")
print("This is because it encourages the model to explain its reasoning process before giving a final answer, which helps identify logic errors and yields higher accuracy for complex nuances.")

,PromptType,MainFeature,WhyUseful
0,Zero-shot,Direct instruction without examples,Quickest to write; tests model’s baseline know...
1,Few-shot,Instruction with a few input-output examples,Improves formatting and accuracy by showing pa...
2,Chain-of-thought,"Asking the model to ""think step-by-step""",Breaks down complex logic; great for reasoning...

Explanation:
For a more difficult text analysis task, I would choose Chain-of-thought prompting.
This is because it encourages the model to explain its reasoning process before giving a final answer, which helps identify logic errors and yields higher accuracy for complex nuances.

## Reflection (optional, no extra points)
Briefly explain the difference between:
- sentiment analysis
- text classification
- prompt engineering

1. Sentiment Analysis
This is a specific type of text analysis used to determine the emotional tone behind a body of text.

Goal: To identify whether a piece of writing is positive, negative, or neutral (and sometimes specific emotions like angry, happy, or frustrated).

Use Case: Analyzing customer reviews, monitoring social media brand mentions, or gauging public opinion on a topic.

2. Text Classification
This is a broader "umbrella" category that involves assigning predefined labels to a piece of text based on its content.

Goal: To organize text into organized groups.

Relationship: Sentiment Analysis is actually a form of Text Classification (where the labels are "Positive," "Negative," etc.).

Other Use Cases: Spam detection (labeling email as "Spam" or "Not Spam"), topic labeling (labeling news as "Sports," "Politics," or "Tech"), and intent recognition in chatbots.

3. Prompt Engineering
Unlike the first two, which are tasks or outcomes, this is a technique or method for interacting with Generative AI (like LLMs).

Goal: To craft, refine, and optimize "prompts" (inputs) to get the most accurate or high-quality response from an AI model.

Key Difference: While you can use Prompt Engineering to perform sentiment analysis or text classification (by telling an AI "Classify this text..."), it is the process of communication with the model rather than the specific task of labeling data.